/* QuickGrade service worker.
 *
 * Purpose: once a teacher has loaded the hosted page, the whole app keeps
 * working with no network — in a classroom with bad wifi, on a cart, offline.
 * It caches only the app's own files. Student data never goes through here;
 * that lives in IndexedDB on the device and is never uploaded.
 *
 * CACHE and SHELL below are generated by build.py from the actual files:
 * the cache name is a hash of their contents, so it changes exactly when
 * something cached changes, and the list cannot fall behind. Editing them
 * by hand will be overwritten on the next build.
 *
 * They used to be maintained by hand with a comment asking whoever edited
 * the app to remember. Nobody remembers, and the two failures are quiet:
 * a stale name ships an update nobody receives, and a stale list leaves a
 * file the app needs simply missing when offline.
 */
var CACHE = 'quickgrade-462da285317f';
var SHELL = [
  './',
  './index.html',
  './css/app.css',
  './js/lib.js',
  './js/i18n.js',
  './js/lang/en.js',
  './js/lang/ar.js',
  './js/lang/hi.js',
  './js/lang/tl.js',
  './js/lang/ru.js',
  './js/lang/th.js',
  './js/lang/ko.js',
  './js/ooxml.js',
  './js/exportmap.js',
  './js/parse.js',
  './js/scoring.js',
  './js/mastery.js',
  './js/vendor/qrcode.js',
  './js/vendor/jsqr.js',
  './js/sheet.js',
  './js/vision.js',
  './js/synth.js',
  './js/scan.js',
  './js/privacy.js',
  './js/app.js',
  './manifest.webmanifest',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE)
      // addAll fails the whole install if any one file 404s, so add
      // individually and let the rest succeed.
      .then(function (c) {
        /* addAll fails the whole install if any one file 404s, so add
         * individually and keep what landed. Swallowing the rejection is
         * right; not counting what survived is not. */
        return Promise.all(SHELL.map(function (u) {
          return c.add(u).then(function () { return u; }, function () { return null; });
        }));
      })
      .then(function (results) {
        var got = results.filter(Boolean);
        /* This used to resolve whatever happened, so skipWaiting() ran on a
         * cache holding 26 files or none, and an active worker with an empty
         * cache answered navigations from a fallback that was not there.
         * Failing the install instead leaves the previous worker in place and
         * the app online, which is a worse offline story and a much better
         * honest one.
         *
         * The floor is the two entries the fetch handler actually depends on,
         * plus a proportion set well under the real count so it catches a
         * truncated install without needing to be edited as SHELL grows. */
        var haveShell = got.indexOf('./index.html') >= 0 && got.indexOf('./') >= 0;
        if (!haveShell || got.length < Math.ceil(SHELL.length * 0.8)) {
          throw new Error('offline install incomplete: cached ' + got.length +
                          ' of ' + SHELL.length +
                          (haveShell ? '' : ', and the page shell is not among them'));
        }
        return self.skipWaiting();
      })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  /* Network-first for navigations so a redeployed app is picked up promptly,
   * falling back to cache when offline. Cache-first for everything else. */
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).then(function (res) {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
        return res;
      }).catch(function () {
        return caches.match(req).then(function (r) {
          return r || caches.match('./index.html');
        }).then(function (r) {
          /* respondWith(undefined) is a bare network error with nothing to
           * read. If the shell is not cached either, say which of the two
           * things went wrong. */
          return r || new Response(
            '<!doctype html><meta charset="utf-8">' +
            '<title>QuickGrade is offline</title>' +
            '<p style="font:16px system-ui;margin:3em auto;max-width:34em">' +
            'QuickGrade cannot load. The network is unavailable and the offline ' +
            'copy was never stored on this device, so there is nothing to fall ' +
            'back to. Reconnect once and reload to store it.</p>',
            { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        });
      })
    );
    return;
  }

  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.status === 200 && res.type === 'basic') {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      });
    })
  );
});
